### PR TITLE
Improvement: 238 fix design discrepancies

### LINKED ISSUE #222: Selection Hitbox only on text and not on area for Navbar
**Component**:
Navbar

**What happened**:
when clicking on the component "Navbar with only link tabs", the hovering is ok on the area, but the selection is only on the text.

https://user-images.githubusercontent.com/28654802/103910389-0ece0080-5105-11eb-8f4f-199cbb8a2226.mp4

Example:
**Resolution proposal** (optional):
to make the selection action on the area, and not only on the text.

### LINKED ISSUE #238: Discrepancies between the design and current implementation
**Component**: checkbox, sidebar, button, notification, navbar, breadcrumb

**Why this is needed**: 
Given core-ui is the basis to keep the consistency between different UI applications, we need to make sure core-ui is up to date with the design.

**What should be done**:
- The chosen item of lateral navbar should have the right-side highlight 
- Update the  `<Button/>` of `size = default`. Keep smaller/small/large/large as it is today.
    - the height of the button should 32px
    - Horizontal spacing: 16px
    - For button has an icon, the padding between icon and text should be 8px. 
image

- `<Checkbox/>` style to be updated
image

- Remove the glow radius of `<Notification/>`
- The width of the collasipd `<Sidebar/>` should be 40px
- Bug fix the selection of the navbar and breadcrumb. Please see: (https://github.com/scality/core-ui/issues/222)
- Update the background color for `<Tabs/>` as we have done for MetalK8s UI according to the design. 
https://www.sketch.com/s/f7ae733f-222f-4335-b742-a86d25dda872/a/a4YdnZ#Inspector
```js
  .sc-tabs-item {
    background-color: ${(props) => props.theme.brand.border};
  }
 ```
- (Maybe) Style the scrollbar(by JS)

**Implementation proposal** (strongly recommended):
Please check Miro for more details.
https://miro.com/app/board/o9J_lWWXfu8=/

Tip to structure the commit:
Ideally, one commit solves one point.

**Test plan**:
Highly recommend testing in Metalk8s to make sure there is no regression. 
Feel free to open PR on **Metalk8s UI** repo if anything mandatory to change or replace the old components with the new ones.

### PR DESCRIPTION
**Pull request by alexis-ld**
**Component**:
Sidebar
Button
Notification
Checkbox
Navbar
Tabs

**Description**: We wanted components to be better aligned with the design following what is described in #238

Sidebar now has an highlighted active item even when collapsed.
Adjusted Sidebar width
Adjusted Buttons dimensions
Removed notification radius glow
Fixed navbar clickable areas
Updated Tabs design to match the design
Updated Checkbox design to match the design

**Design**: Updated to fit to the design following specs from #238 

**Breaking Changes**: none

- [] Breaking Changes

---

Closes: #238 
Closes: #222

### CODE REVIEW

File: src/lib/components/button/Button.component.js [hunk 1]
```diff
@@ -20,7 +20,7 @@ type Props = {
   title?: string,
```
Comment (ChengYanJin) [inline src/lib/components/button/Button.component.js:20]: Can you please fix the Button Loading stories? Maybe not directly related to your changes though.

File: src/lib/components/tabs/Tabs.component.js [hunk 2]
```diff
@@ -51,6 +56,9 @@ const TabItemTitle = styled.p`
   margin: 0;
   font-size: ${defaultTheme.fontSize.large};
```
Comment (ChengYanJin) [inline src/lib/components/tabs/Tabs.component.js]: Please update the fontsize to 14px.

**Review by ChengYanJin — CHANGES_REQUESTED** [review]

**Review by ChengYanJin — APPROVED** [review]
